name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda diariamente à meia-noite (UTC)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: AndBalbino
          outputs: |
            ./dist/github-contribution-grid-snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 🐍 Atualizando snake dos commits
          add: './dist/github-contribution-grid-snake.svg'
